---

- name: "Primer playbook"
  hosts: all
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"

  tasks:
    - name: "Output some information on our host"
      ansible.builtin.debug:
        msg: "Me estoy conectando a {{ ansible_nodename }} corriendo la distro {{ ansible_distribution }}"
